Create gdx frontend
Traffic-simulator/traffic-simulator pull request #3
Opened 2024-11-09 13:26 UTC by TheBlek

Бек, проверьте пж, что я ничего не сломал у вас

2024-11-09 13:42 UTC, MurenMurenus requested changes

2024-11-09 13:42 UTC, MurenMurenus commented on build.gradle
> -    implementation(project(":simulator"))
Вот эти три штуки нужны нам для работы кода из подмодулей

2024-11-09 13:42 UTC, MurenMurenus commented on build.gradle
> -    implementation(project(":simulator"))
Вижу ниже subprojects, но не знаю, как оно работает. Мб можно там указать, но это надо будет тестить на работоспособность

2024-11-09 13:42 UTC, MurenMurenus commented on frontend/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
Кэши точно нужны? Просто вдруг случайно попало

2024-11-09 13:42 UTC, MurenMurenus commented on gradle/wrapper/gradle-wrapper.properties
Давай пока не мерджить с новой версией градла, я завтра протестирую на 8.10 и отпишу сюда

2024-11-09 13:45 UTC, TheBlek commented on frontend/build/kotlin/compileKotlin/cacheable/caches-jvm/inputs/source-to-output.tab
Блин, там вся папка билда в гит попала

2024-11-09 13:52 UTC, TheBlek commented on build.gradle
> -    implementation(project(":simulator"))
Тоже хз, что оно делает. Потестите пж

2024-11-09 13:58 UTC, TheBlek commented on build.gradle
> -    implementation(project(":simulator"))
Вернул какие-то вещи еще. У меня вроде все модули собираются

2024-11-10 04:08 UTC, MurenMurenus requested changes

2024-11-10 04:08 UTC, MurenMurenus commented on gradle/wrapper/gradle-wrapper.properties
окей, оно работает

2024-11-10 04:08 UTC, MurenMurenus commented on xodr_parser/build.gradle
> +    jvmToolchain(21)
Поменяй тогда и в simulator модуле jvm на 21ую, иначе он ловит конфликт

2024-11-10 04:08 UTC, MurenMurenus commented on build.gradle
> -    implementation(project(":simulator"))
окей, хорошо

2024-11-10 06:28 UTC, Rustam-Khamidullin approved these changes
Запустил у себя на винде и на линуксе. Все работает, но на линуксе вылазят ворнинги, что wayland не поддерживает некотрые функции, но думаю пока пофиг.

2024-11-10 07:12 UTC, TheBlek commented on xodr_parser/build.gradle
> +    jvmToolchain(21)
Поправил

2024-11-12 07:26 UTC, MurenMurenus approved these changes

2024-11-12 07:27 UTC, merged